# AzipediaSearcher YamlConfiguration
# Plugin Version
version: 1.0

# 言語設定
# デフォルトでは日本語です
language: "ja"

# 検索するMediaWikiのURLを設定してください
# /api.phpとなるようにしてください
# 例：http://ja.wikipedia.org/w/api.php
# 　　この場合、.../w/までを設定してください
BaseUrl: "https://wiki.azisaba.net/"

# /wiki searchコマンドのクールダウンを設定します
cooldown: 10